version: '3.2'
services:
  postgresql:
    image: postgres:10.4
    volumes:
      - ./postgresql/:/var/lib/postgresql/data/
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    command: --spring.profiles.active=prod
    ports:
      - 5432:5432