spring:
  datasource:
    url: jdbc:mysql://localhost/authentication
    username: root
    password: password

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never