spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: marcos
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      ddl-auto: update

server:
  tomcat:
    accesslog:
      enabled: true
  error:
    include-stacktrace: never

hibernate:
  globally_quoted_identifiers: true